using Microsoft.EntityFrameworkCore;
using TechChallenge.Api.Endpoints;
using TechChallenge.Api.Middleware;
using TechChallenge.Infrastructure.Database.Context;
using TechChallenge.Infrastructure.IoC.Injection;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddOpenApi();
builder.Services.AddSwaggerGen();
builder.Services.AddInfrastructure(builder.Configuration);

var app = builder.Build();

if (!app.Environment.IsEnvironment("Testing"))
{
    using var scope = app.Services.CreateScope();
    var context = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
    context.Database.Migrate();
}

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{

}

app.UseMiddleware<ExceptionMiddleware>();

app.MapOpenApi();

app.UseSwagger();
app.UseSwaggerUI(options =>  // Configures the Swagger UI to use the OpenAPI document generated by MapOpenApi
{
    options.SwaggerEndpoint("/openapi/v1.json", "TechChallenge API");
});
app.UseHttpsRedirection();

app.MapClientesEndpoints();
app.MapFuncionariosEndpoints();
app.MapVeiculosEndpoints();
app.MapServicosEndpoints();
app.MapInventarioEndpoints();
app.MapOrdensServicoEndpoints();

app.Run();
