apiVersion: v1
kind: ConfigMap
metadata:
  name: techchallenge-api-config
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_HTTP_PORTS: "8080"
  Http__UseHttpsRedirection: "false"
  Seed__AdminLogin: "admin"
  Seed__FakeData: "false"
  Seed__DemoData: "false"
  Jwt__Issuer: "techchallenge-api"
  Jwt__Audience: "techchallenge-clients"
  Jwt__AccessTokenMinutes: "15"
  Jwt__RefreshTokenDays: "7"
  ApprovalLinks__BaseUrl: "http://localhost:18080"
  ApprovalLinks__ExpirationHours: "48"
