<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Domain\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Domain\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Domain\**" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TechChallenge.Application.Abstractions\TechChallenge.Application.Abstractions.csproj" />
      <ProjectReference Include="..\TechChallenge.Domain\TechChallenge.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.1.1" />
    </ItemGroup>

</Project>
