@baseUrl = http://localhost:8080

# Preencha apos executar o passo 10 do arquivo 02.
@codigoAcompanhamento = cole-o-codigo-aqui

### Acompanhamento publico da OS
GET {{baseUrl}}/api/v1/ordens-servico/acompanhamento/{{codigoAcompanhamento}}
Accept: application/json

### Tempo medio de execucao
GET {{baseUrl}}/api/v1/ordens-servico/tempo-medio-execucao
Authorization: Bearer {{vendedorToken}}
Accept: application/json

### Fila operacional priorizada da oficina
GET {{baseUrl}}/api/v1/ordens-servico/oficina
Authorization: Bearer {{vendedorToken}}
Accept: application/json
